while True:
    basic.show_icon(IconNames.SMALL_DIAMOND)
    basic.pause(100)
    basic.show_icon(IconNames.DIAMOND)
    basic.pause(100)
    basic.show_icon(IconNames.TARGET)
    basic.pause(100)
    basic.show_icon(IconNames.DIAMOND)
    basic.pause(100)
    basic.show_icon(IconNames.SMALL_DIAMOND)
    basic.pause(100)
    basic.show_icon(IconNames.SMALL_HEART)
    basic.pause(100)
    basic.show_icon(IconNames.HEART)
    basic.pause(100)
    basic.show_icon(IconNames.HAPPY)

